### ISSUE TITLE
Landcover names are cut

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1135]
The name of this school is cut in zoom 18:
http://www.openstreetmap.org/way/224161682#map=18/50.77231/6.04276
Tiles are fresh rendered, the osm data is at least a few month old, surrounding objects are not very large.
It is not a big issue and i do not know if this is solvable, but seems like bug to me.

**Comment by pnorman** [comment]
#1332 example

![43861](https://cloud.githubusercontent.com/assets/1190866/6422736/d6310342-be90-11e4-87d4-245ecbe39589.png) ![43861](https://cloud.githubusercontent.com/assets/1190866/6422740/db7c40b4-be90-11e4-9566-29851100c575.png)

**Comment by math1985** [comment]
Adding marker-clip: false; to all landcover labels would solve this,

Would this be unacceptable for performance reasons?

**Comment by tilmanb** [comment]
This does also happen to railway stations, see http://www.openstreetmap.org/node/1280821133#map=17/51.04257/13.75601 .

![dresden-bahn-manuf](https://cloud.githubusercontent.com/assets/779297/6710140/ef4fdc20-cd7e-11e4-9f96-414c1a9e98d3.PNG)

**Comment by matkoniecz** [comment]
@tilmanb Broken railway station labels was reported as #1356 and fixed by #1357, fix will be included in the next version

**Comment by math1985** [comment]
> @tilmanb Broken railway station labels problem was reported as #1356 and fixed by #1357, fix will be included in the next version of map style.

If I'm not mistaken, this will only fix cut-off of the square station icon, not of the name.

**Comment by matkoniecz** [comment]
@math1985 At least in some cases #1357 fixed also station name, see https://github.com/gravitystorm/openstreetmap-carto/issues/1356#issuecomment-77526328

**Comment by Hedaja** [comment]
Here is another example where this happens:
http://www.openstreetmap.org/node/2251164072#map=18/51.05185/13.77631&layers=N

**Comment by scaidermern** [comment]
> @tilmanb Broken railway station labels problem was reported as #1356 and fixed by #1357, fix will be included in the next version of map style.

It is still broken at zoom level 17. Interestingly at the same longitude as the examples linked by tilmanb and pnorman.

**Comment by n9** [comment]
Any ideas how to fix this issue?

PS: Why sometimes the same labels are correct when crossing tiles and sometimes not?

![osm-broken-labels](https://cloud.githubusercontent.com/assets/1651867/15858423/b032a930-2cc0-11e6-9cdf-98b2f56b2bba.png)

**Comment by math1985** [comment]
> Any ideas how to fix this issue?

No, I'm not sure.

> PS: Why sometimes the same labels are correct when crossing tiles and sometimes not?

I think this has to do with tile boundaries versus metatile boundaries, see for example https://www.mapbox.com/tilemill/docs/guides/metatiles/ (they talk about Tilemill but for any software using Mapnik it works similar).

**Comment by floscher** [comment]
@n9 I think in your case the area has simply been edited recently and not all tiles were already re-rendered.

That is normal and acceptable, because this will disappear on its own soon after an edit. The problematic case is when all affected tiles are rendered with the latest data and names are still cut.

In the meantime the labels are complete again for your example:
http://osm.org/go/0LHNzyC

**Comment by n9** [comment]
@math1985 The visible grid is metatiles boundary. (The output is from kosmtik.) Both labels are across metatile boundary.

@floscher I have downloaded a snapshot of OSM into postgres and rendered using kosmtik. So it is not a editing problem. (All tiles are rendered at the same time from the unchanged OSM db.)

I have set buffer-size to 256 and I was trying buffer-size even 2560. It does not help. (Only lowering buffer-size add more cut off labels.

Does anyone know what version of openstreetmap-carto and mapnik is openstreetmap.org currently using?

**Comment by matkoniecz** [comment]
> Does anyone know what version of openstreetmap-carto and mapnik is openstreetmap.org currently using?

See https://github.com/openstreetmap/chef/blob/master/roles/tile.rb#L81

With mapnik I am not sure - see https://github.com/openstreetmap/chef/search?utf8=%E2%9C%93&q=mapnik

**Comment by HolgerJeromin** [comment]
All linked examples are working now. 
Perhaps solved with a real fix or different wrapping now (at a "-") with upstream software changes. 
Close the issue?

**Comment by nebulon42** [comment]
Let's close and re-open if happening again.
