### ISSUE TITLE
Render emergency=lifeguard facilities

### ISSUE THREAD

**Issue by Fizzie41** [gravitystorm/openstreetmap-carto#3629]
Currently, none of the emergency=lifeguard options render.

Visibility of these facilities on the map could well be (without wanting to sound over-dramatic!) a matter of life or death, in that people can see where to go for help if a swimmer is in trouble.

If placing a node using iD, emergency=lifeguard does show an black & white life-ring icon, but it doesn't actually then render on the map eg https://www.openstreetmap.org/node/3491121545.

A better icon would be the one shown on the emergency=life_ring page https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlife_ring: https://wiki.openstreetmap.org/w/images/0/0a/Life_ring.png
as red is the global distress / emergency colour & would stand out better on the map.

The same icon should be used for all the lifeguard options ie
https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlifeguard
https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlifeguard_base
https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlifeguard_tower
https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlifeguard_platform
https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dwater_rescue_station
https://wiki.openstreetmap.org/wiki/Tag%3Aemergency%3Dlife_ring 

There are ~2000 of these facilities worldwide, so it is not an insignificant matter.

**Comment by jeisenbe** [comment]
Several of these tags are debated on the wiki, eg the water rescue station
page says “It has been proposed that this page or section be merged with
Tag:emergency=lifeguard_base”. Each has a couple hundred uses.

Perhaps this could be discussed on the tagging mailing list first.

The last tag, emergency=life_ring is quite different from the others, it
represents a device rather than a service. It has just over 2000 uses.
Perhaps it could have an icon in man-made gray color at z19 only?

Joseph

**Comment by wilmaed** [comment]
> emergency=life_ring

For me the most interesting tag:

1) usage: 2083 
https://taginfo.openstreetmap.org/tags/?key=emergency&value=life_ring

2) life saving (not for current emergency situation, but for preparation)


ID-Editor Icon:
![ring](https://user-images.githubusercontent.com/31799538/50961927-4f202700-14c9-11e9-919b-c9c18ca7fe90.png)

**Comment by kocio-pl** [comment]
Please test it on 14 px matrix to see how is it working.

**Comment by wilmaed** [comment]
> 
> 
> Please test it on 14 px matrix to see how is it working.
Icon 14x14
![g305](https://user-images.githubusercontent.com/31799538/50963656-98727580-14cd-11e9-86b3-69d22743d0fb.png)

Beach:
![beach](https://user-images.githubusercontent.com/31799538/50964503-c48ef600-14cf-11e9-9f44-ef1cb391bfbf.png)

**Comment by kocio-pl** [comment]
I guess I would try a bit bigger white areas and use healthcare red probably, but it looks acceptable detail for me for z19+.

![taghistory 40](https://user-images.githubusercontent.com/5439713/50965128-66fba900-14d1-11e9-9cc1-654504739f4b.png)

**Comment by wilmaed** [comment]
> 
> 
> I guess I would try a bit bigger white areas and use healthcare red probably,

14x14 red/white
![r2](https://user-images.githubusercontent.com/31799538/50966058-15085280-14d4-11e9-8311-2ecf798cc086.png)

Beach2:
![beach2](https://user-images.githubusercontent.com/31799538/50966465-45042580-14d5-11e9-9cc6-83652abafcac.png)

**Comment by wilmaed** [comment]
Beach3: transparent inner ring

![beach2](https://user-images.githubusercontent.com/31799538/50967157-97464600-14d7-11e9-9246-405f84a7351d.png)

**Comment by Adamant36** [comment]
Is that an actual test rendering with a .png file or just a cut and past?

**Comment by kocio-pl** [comment]
What we need is probably SVG icon with red and white colors included. Having more than one color defined does not allow to make color styling on the fly by Mapnik, but it's still plain XML code that can be easily changed by text editor.

**Comment by wilmaed** [comment]
> What we need is probably SVG icon with red and white colors included. 

for red: which rgb-Value?

**Comment by Adamant36** [comment]
Sorry, I meant SVG. Empty space where the white spots should be would be better wouldn't it?

**Comment by kocio-pl** [comment]
> for red: which rgb-Value?

I guess reusing healthcare red would be OK (it might be changed - see #3613 - but it's easy to update SVG then):

https://github.com/gravitystorm/openstreetmap-carto/blob/762b292b7ab9d353ed1fd99adabe6c44070977d4/amenity-points.mss#L10

> Empty space where the white spots should be would be better wouldn't it?

One has to test it. It didn't work for me for bus stations, but maybe this icon is different.

**Comment by wilmaed** [comment]
SVG (only 2 colors: transparent and red):
https://github.com/wilmaed/foo/blob/master/ring_trans.svg

14x14px:
![zwischenablage01](https://user-images.githubusercontent.com/31799538/50971011-49cfd600-14e3-11e9-9d1e-e6bc91c3ff2b.png)

Beach3:
![beach3](https://user-images.githubusercontent.com/31799538/50971824-4dfcf300-14e5-11e9-9069-bcb1a9679a5f.png)

**Comment by wilmaed** [comment]
> Is that an actual test rendering with a .png file or just a cut and past? (probably a cut and paste now that I actually looked at it).

I am only able to c&p: 14x14px on Zoom-Level 19.

> Sorry, I meant SVG. Empty space where the white spots should be would be better wouldn't it?

https://github.com/wilmaed/foo/blob/master/ring_trans.svg

Tranparence instead of white.
A test rendering is beyond my knowledge.

**Comment by matkoniecz** [comment]
>  a matter of life or death, in that people can see where to go for help if a swimmer is in trouble

For record this is quite absurd justification, if lifeguard location is so far away that one needs map to find them - then they arrive far too late to help

**Comment by jragusa** [comment]
Other lifeguard facilities would be better rendered with this icon. The proposed icon stands out too much for just a life ring in comparison to `waste_basket` for example.

**Comment by kocio-pl** [comment]
> Other lifeguard facilities would be better rendered with this icon. 

Which ones do you mean?

**Comment by jragusa** [comment]
I mean `emergency=base/tower/plateform/water_rescue_station` but I notice they are not so frequent (total=1257).

**Comment by Fizzie41** [comment]
Thanks everyone for your work!

Could I suggest using only 4 quadrants as per https://wiki.openstreetmap.org/w/images/0/0a/Life_ring.png
0-90` white, 90-180 red, 180-270 white & 270-360 red?

Would that show up better?

**Comment by Fizzie41** [comment]
> Other lifeguard facilities would be better rendered with this icon. The proposed icon stands out too much for just a life ring in comparison to `waste_basket` for example.

I did suggest using this icon for all of the various lifeguard facilities as well as stand-alone life-rings.

& (even though Mateusz doesn't agree), if they are showing a potentially life-saving object / facility, doesn't that make them quite a bit more important than a waste basket?

**Comment by Fizzie41** [comment]
> What @matkoniecz explained is that “saving live” is a really bad argument for rendering of this icon! The process of drowning is usually very short (often shorter than 60 seconds!), so it’s useless to use a map to find a life guard station to get someone saved.

Respectfully, I disagree.

I live at one of the top tourism destinations in Australia, with a major emphasis on beaches / swimming / surfing. We regularly (weekly?) see reports of people being rescued because someone saw they were in trouble, then ran several 00 m's along the beach to get help.

Frequently, these people have got into trouble as they were swimming in the wrong spot on the beach. This proposal "could" even help reduce that happening, as it would show where lifeguards are located, & so "may" help people decide to go to a safe place?

**Comment by Adamant36** [comment]
99% agree its probably worthless to look at the map in order to find this information at the time of a rescue. It doesnt mean it wouldnt be worth seeing ahead of time though when planing a trip as an orentation point, knowing where life guards are or if the beach your going to has safety equipment in the first place or not (some dont. So might not be worth going compared to one nearby that does), or even when your at the beach and want to talk to a life guard but not for an imidate risk in the water (they still provide useful safty information, bandaides, splents, whatever). I think preplanning what beach to go to and as an emergency orentation point is the best use case. Its a big part of "beach Infrastructure."

**Comment by Fizzie41** [comment]
> Also, for places which aren't sunny all year round, lifeguards may only be operational for the summer months - not sure if there's anything that can be done to show the difference?

This was mentioned in the original mailing-list discussion re lifeguards, with thought of using the opening hours key with comments eg "May - October only", which would mean that people would have to check the details on each particular node.

So what happens from here please? Is there anything further that needs to be done, or will this just start rendering on the next update? How does it all work?

Thanks

**Comment by kocio-pl** [comment]
As it seems acceptable goal, someone needs to make a code for rendering life-rings. Maybe you would like to try?

**Comment by Fizzie41** [comment]
Sorry, I thought that had all been worked out up there ^, with the final option being red & white colours with a transparent centre?

> Maybe you would like to try?

Thanks, but I don't have the faintest idea of even how / where to start!

**Comment by kocio-pl** [comment]
> Sorry, I thought that had all been worked out up there ^, with the final option being red & white colours with a transparent centre?

I think so. Now the design decision needs to be coded.

>Thanks, but I don't have the faintest idea of even how / where to start!

The usual way of starting is with reading this:

https://wiki.openstreetmap.org/wiki/Standard_tile_layer
https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by da1910** [comment]
I'll take this if nobody else is working on it. Rendering life_ring is easy enough (currently I've used health_red at z19). Regarding the other tags, I can add them for rendering if/when consensus is reached?
![screenshot from 2019-02-01 16-11-19](https://user-images.githubusercontent.com/12086549/52134736-2e686e80-263c-11e9-84ba-30cbd162365d.png)
![screenshot from 2019-02-01 16-11-31](https://user-images.githubusercontent.com/12086549/52134738-2f010500-263c-11e9-80c8-dccde82eb4a6.png)

**Comment by da1910** [comment]
Regarding the other tags mentioned above, I think there's merit to having an icon rendered for manned lifeguarding/rescue facilities, possibly something like a tower with a lifering or similar.

**Comment by Fizzie41** [comment]
I agree with you - my original suggestion was just to have the same life-ring icon render for each facility

**Comment by da1910** [comment]
I wonder if it's worth rendering some kinds of lifeguard facilities at lower zoom levels, likely rendering manned lifeguard stations before life rings? If that looks good then I'll put in a pull request for this.

**Comment by da1910** [comment]
Ok, so there's been tagging discussion about lifeguard facilities it seems for a couple of years now over on the osm wiki, and there's been no consensus so far. I'd initially render lifeguard_base and lifeguard_tower, as they are the two most common tags from the bunch.
Here's a couple of test renderings in Germany, currently rendering at z=16+ for manned facilities, I'd be wary of rendering life rings at lower zoom levels, they're more likely to be in crowded spaces and I think the argument above about utility is valid.
I haven't put the PR in yet for life rings, it'll take a little while for it to be discussed and merged if the maintainers agree once that's done
![screenshot from 2019-02-20 13-29-23](https://user-images.githubusercontent.com/12086549/53095108-d70b3f00-3513-11e9-89cc-bcbdd53b95f0.png)
![screenshot from 2019-02-20 13-32-50](https://user-images.githubusercontent.com/12086549/53095182-0c179180-3514-11e9-8fcd-e35cae369915.png)

**Comment by da1910** [comment]
With life ring rendering decided upon, i do believe that the remaining facilities need rendering, and my logic for rendering lifeguard_tower and lifeguard_base is the following:

> Of the lifeguard facilities that are tagged the two most popular are lifeguard_base (278 uses) and lifeguard_tower (489 uses), there has been discussion ongoing for a while about merging some of the lifeguard facility tags, but no consensus was reached. My rationale would be that lifeguard_base would represent permanently manned facilities with storage and maintenance facilities, like RNLI lifeboat stations in the UK. While lifeguard_tower would represent buildings that are manned seasonally and have limited to no facilities, but that immediate assistance would be available when open.

I'd love to get some consensus on what ought to be rendered here.

**Comment by da1910** [comment]
A comment on the pull request above suggested that the icon is a little heavy, do we have a lighter weight version of the icon that could be used instead? @wilmaed perhaps?

**Comment by Fizzie41** [comment]
Just wondering if we were ever able to come up with a solution for the Life-ring? I see form reading 3688 that it's been decided not to do anything about the various bases / towers etc, but life-ring seems to be OK? Thanks

**Comment by imagico** [comment]
We have an open PR in #3688 but the issues mentioned in https://github.com/gravitystorm/openstreetmap-carto/pull/3688#issuecomment-466060761 have so far not been addressed.  More generally speaking new symbol types are currently difficult to find consensus for due to the lack of consensus on #3635 and an overall strategy for POI rendering.

**Comment by da1910** [comment]
I'm very happy to implement this request with a new icon, but I am by no means a designer, so if someone wants to propose an improved icon then I can do the fix. It's unlikely to get merged unless there is clear consensus here and on the PR. Feel free to support the addition of Life-Rings over on PR #3688 if the issue matters to you!

**Comment by Fizzie41** [comment]
On Tue, 14 Jan 2020 at 01:02, Doug Addy <notifications@github.com> wrote:

> I'm very happy to implement this request with a new icon, but I am by no
> means a designer, so if someone wants to propose an improved icon then I
> can do the fix.
>

Thanks, Doug!


> It's unlikely to get merged unless there is clear consensus here and on
> the PR. Feel free to support the addition of Life-Rings over on PR #3688
> <https://github.com/gravitystorm/openstreetmap-carto/pull/3688> if the
> issue matters to you!
>

As I mentioned above, I'm not too sure what has to be done?

  Thanks

Graeme

>

**Comment by Fizzie41** [comment]
On Wed, 8 Jan 2020 at 05:10, Christoph Hormann <notifications@github.com>
wrote:

> We have an open PR in #3688
> <https://github.com/gravitystorm/openstreetmap-carto/pull/3688> but the
> issues mentioned in #3688 (comment)
> <https://github.com/gravitystorm/openstreetmap-carto/pull/3688#issuecomment-466060761>
> have so far not been addressed.
>
Thanks (& apologies for delay in replying)

Sorry, but is that then up to me to correct / consolidate / update or
whatever?

  Thanks

Graeme

>

**Comment by Fizzie41** [comment]
Comment added to #3688 suggesting using this icon for emergency=life_ring initially.
https://github.com/gravitystorm/openstreetmap-carto/pull/3688#issuecomment-753240220

**Comment by EwenH** [comment]
> > a matter of life or death, in that people can see where to go for help if a swimmer is in trouble
> 
> For record this is quite absurd justification, if lifeguard location is so far away that one needs map to find them - then they arrive far too late to help

Not exactly. We have multiple incidents in Australia where the passer by rescuers have perished as well and in that time, there could have been potentially an improved outcome. For the state that I am in over the last summer "The 2019-20 Victorian Drowning Report shows there were 34 drowning deaths in Victoria and 100 non-fatal drowning incidents last financial year." This current season 42 people have drowned in Victoria since July (winter), 2020 to January 2020.

**Comment by Adamant36** [comment]
Personally, I'd argue it might be worth rendering emergency=lifeguard. Since it could help people know where it is safer to swim. I'm sorta against rendering Life-Rings though, because most of the time they are not accessible to the public and people shouldn't be taking life rings in an emergency situation from people who trained in using them and rescuing people.

  don't know how it is anywhere else then America, but everywhere that I have gone swimming life rings are always with life guards or near them and you can't just be like "hey do you mind if barrow that to save someone?" I'm sure there are exceptions, but not enough to make rendering them worth it IMO.

**Comment by Fizzie41** [comment]
> Personally, I'd argue it might be worth rendering emergency=lifeguard. Since it could help people know where it is safer to swim

Since I've been doing further work on this tag, I've wondered about rendering both =lifeguard & also =lifering?

Life-ring would be the icon of an actual life-ring, as discussed here, while lifeguard could be shown as a red & yellow flag, which I believe is in international use to mark a safe swimming area?

> people shouldn't be taking life rings in an emergency situation from people who trained in using them and rescuing people.

No, of course not.

> life rings are always with life guards or near them

Not always. They are often mounted on jetties etc so they are available for anybody to grab & throw to someone in trouble in the water eg https://en.wikipedia.org/wiki/Lifebuoy#Gallery_of_types_of_lifebuoys

> there is a high probability that any particular life ring won't consistently be in the place where it is mapped

Permanent mounts so very unlikely they wouldn't be there, unless it's been stolen / vandalised (& we don't make provision for that in any mapping)

**Comment by Adamant36** [comment]
> lifeguard could be shown as a red & yellow flag, which I believe is in international use to mark a safe swimming area?

I'd have zero problem with that. 

> No, of course not.

So then don't you think that points to the fact that they are not the best things to render for a general map? I guess you could add access=private tags them to get around it, but I don't think that's adequate. 

> Permanent mounts so very unlikely they wouldn't be there, unless it's been stolen / vandalised (& we don't make provision for that in any mapping)

I'm sure there's other instances where the actual life ring wouldn't be there. I'd have problem with this if the permanent mounts are what we were tagging, but we are tagging what's attached to them and there is zero guarantee that it will be there when someone needs to save a persons life with it. I can't think of anything else in OSM that is like that. It's not really a matter of life or death if a vending machine is out of candy bars one day, like it is here if there is no life ring we are rendering the map like there is one. If the tag was for life ring mounts there wouldn't be that problem, because we aren't mapping something that can be easily picked up by anyone and taken away.

**Comment by Fizzie41** [comment]
> So then don't you think that points to the fact that they are not the best things to render for a general map?

Sorry, lifeguards or rings? Regardless, yes, I consider they could both be mapped independently. Lifeguard shows you where you can to fetch help, lifering shows where it is if there's no professional help available.

>  there is zero guarantee that it will be there when someone needs to save a persons life with it.
> I can't think of anything else in OSM that is like that.

Emergency phones, fire hydrants / extinguishers / alarms / water-tanks, first aid kit, AED, drinking water ...
There's no guarantee that at the time they're needed, they'll actually be there / operational / usable, but we still map them.

**Comment by Adamant36** [comment]
> Sorry, lifeguards or rings?

Life rings. If they should be reserved for the professionals that know how to save people and I 99% of mappers don't qualify as those, then it's something to specific for a general purpose map. Lifeguard stations would be perfectly fine to render though. 

> Emergency phones, fire hydrants / extinguishers / alarms / water-tanks, first aid kit, AED, drinking water ...
There's no guarantee that at the time they're needed, they'll actually be there / operational / usable, but we still map them. 

I'm not a big of "other stuff exists" arguments. Especially in cases of things that aren't even rendered. Like is the case for most of the things you listed. In the cases of things that you did list, it would be extremely hard to pick up an emergency phone, water fountain, or water-tank and just walk away with any of them. So, in no way are they analogous. A first aid kit might be, but again, they aren't rendered. So it's moot point. It also is to compare life rings to AEDs, because at least from what I've seen they aren't publicly accessible. There aren't AEDs hanging off the side of random piers and they are usually behind glass that can only be accessed by an employee of where ever they are located. That said, I'd still make the same argument for why they shouldn't be rendered as I am for life rings.

**Comment by Adamant36** [comment]
BTW, some life ring cabinets or mounts might contain other Throwable PFD devices besides life rings like throwable Cushions. A lot of the cabinets are locked though and have no way to tell what is actually inside of them by doing a simple ground survey. So, it would be miss-leading render them as life rings. When that's not what they might actually contain.

**Comment by Fizzie41** [comment]
The proposal has now gone through to approve the tag https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dlifeguard as the main way of indicating the presence of lifeguards at a beach etc. 

Could I suggest / recommend that it should also be rendered with the life-ring icon as discussed above, with that same icon applying to both emergency=lifeguard & also emergency=life_ring?

Thanks

**Comment by Adamant36** [comment]
Personally, I'd be for rendering emergency=lifeguard as a building like building=roof is and the name. I don't think an icon is necessary though. Especially a life ring. Going by the rendering example above it would just needlessly clutter the map. That said, there's still only 1,220 uses of the tag. Which is still extremely low to start considering rendering even if it is an approved tag. Plus, the uses only seem to be centered around a few particular places in the world. Which isn't great either.

**Comment by boothym** [comment]
There's just as many uses of the deprecated tags listed in the OP, so that would double the numbers if they were fixed.

Don't think it's a surprise that the tag usage is centred around places which are well mapped, have lots of coastline, and plenty of people needing looked out for by lifeguards.

But there's other tags like that as well. I mean, I'm not going to complain that natural=volcano is used 5,240 times and are centred around a few particular places (mainly the Pacific ring and Iceland). 😉

**Comment by matkoniecz** [comment]
> rendering emergency=lifeguard as a building like building=roof is and the name

Rendering nonbuildings as buildings would be highly confusing and of questionable benefit

**Comment by Adamant36** [comment]
> Rendering nonbuildings as buildings would be highly confusing and of questionable benefit

It looks like the tag is used on buildings from the Wiki image and description. I assume emergency=lifeguard isn't used to tag an actual life guard. So what else would it be tagged on besides a building?

**Comment by matkoniecz** [comment]
> So what else would it be tagged on besides a building?

In such case rendering them as buildings ads nothing.

**Comment by Fizzie41** [comment]
>  I assume emergency=lifeguard isn't used to tag an actual life guard. So what else would it be tagged on besides a building?

The location where a lifeguard may be found while on duty. That will usually be in either a tower, or a full base, so yes, it would be a building, but you are not tagging the building as such, rather the presence of a lifeguard. 

> That can't be said for beaches though. It shouldn't have to be pointed out that they aren't just along coastlines either. Since there's plenty of non-coastal beaches. Not to mention other bodies of water that have lifeguards

Which doesn't effect the tagging in any way - you can still show the presence of a lifeguard at an inland waterway.

**Comment by Adamant36** [comment]
> In such case rendering them as buildings ads nothing.

I agree. That doesn't answer my question about what else besides buildings it's tagged on though, because when I looked into it that was what it was tagged on and I assume you'd know the answer since your the one that said it is tag on other stuff besides buildings.

> The location where a lifeguard may be found while on duty. That will usually be in either a tower, or a full base, so yes, it would be a building, but you are not tagging the building as such, rather the presence of a lifeguard.

Of course not. But it would be tagging the building in the same that other things contained in buildings that only rendered as their names currently render. It would be really cool if we could skip devolving this discussion into some extensional nonsense like the meaning of the meaning of the word "wall" or "building" or whatever, and just stick to precedent and what's actually reasonable instead. 

> Which doesn't effect the tagging in any way - you can still show the presence of a lifeguard at an inland waterway.

Obviously. Your the one that brought up coastlines.

**Comment by Fizzie41** [comment]
> Your the one that brought up coastlines

When did I say that?

**Comment by Adamant36** [comment]
> Sorry, when did I say that?

Actually you didn't. It was actually @boothym. That's what I get for doing this on the phone 🤣

**Comment by jidanni** [comment]
I like how iD does it, except one little thing, 
https://github.com/openstreetmap/iD/issues/9832 .
