### ISSUE TITLE
Please render Outdoor Seating Area as an area

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4792]
Outdoor Seating Areas can be very well defined by a terraces, fences, or whatever.
In that case  I draw it along those boundaries.

I would expect it to be rendered that way.

But currently only a symbol is planted.

It would give a much better understanding if the area was actually drawn.

Just one of the many samples: [Hero](https://www.openstreetmap.org/edit#map=22/52.13991/5.24178).

Thanks.

**Comment by HolgerJeromin** [comment]
> Just one of the many samples: Hero.

To save some clicks: This is https://www.openstreetmap.org/way/1155847666
with `leisure=outdoor_seating`
![image](https://user-images.githubusercontent.com/2410353/226547069-872f4c26-884e-457a-adfa-b70069c2a3b9.png)

**Comment by tjur0** [comment]
We could reuse the area rendering for amenity parking?
In some ways you can say outdoor seating is like parking for humans.

**Comment by BertMule** [comment]
> What do you propose as a rendering that won't be confused with something else?

I would say:
- A boundary.
- Some filling, but not even necessary.
- For clarity: the icon inside the boundary.

**Comment by tjur0** [comment]
same as amenity=parking
![image](https://user-images.githubusercontent.com/46526540/226679698-92a1dc8c-c8ef-4338-a3f2-30c67f48af75.png)
same as highway=pedestrian
![image](https://user-images.githubusercontent.com/46526540/226680619-d2152e71-c6f7-47f9-a1b8-da07e3456726.png)
50% mix
![image](https://user-images.githubusercontent.com/46526540/226681612-4c67cc9f-7198-4154-a52c-08897b5d3faa.png)

area used: https://www.openstreetmap.org/#map=19/52.41622/5.29884

**Comment by swedneck** [comment]
I would probably vote for 50% mix, though maybe you could find an example showing how it looks next to both parking and pedestrian areas?

**Comment by tjur0** [comment]
Found some in Leeuwarden!
https://www.openstreetmap.org/way/685270953#map=19/53.21153/5.79626
![image](https://user-images.githubusercontent.com/52704747/226703951-b4f31ce1-db5b-4e72-a069-542143b08378.png)
https://www.openstreetmap.org/way/1075326905#map=19/53.20150/5.79173
![image](https://user-images.githubusercontent.com/52704747/226704036-5b6f33ee-46e5-4da4-a0fc-8a5028b99390.png)
https://www.openstreetmap.org/way/993255735#map=19/53.20050/5.79980
![image](https://user-images.githubusercontent.com/52704747/226704180-92f0271b-b133-4fae-a826-195aeec23d21.png)

**Comment by swedneck** [comment]
I like it!

**Comment by BertMule** [comment]
I could live with any of those. 
But some distinctive colour would be nice.

Thanks for your input.

**Comment by hungerburg** [comment]
The colour would have to be either leisure green or amenity brown:

![OutdoorSeating](https://user-images.githubusercontent.com/586972/230737451-6125256f-efdb-4009-b561-7e5e396beaa0.png)

**Comment by IgorEliezer** [comment]
They could be transparent with a subtle gray outline, since those areas are part of a commercial/retail landuse, park or pedestrian area. A seating area usually has the same surface as the surrounding area, it's just a fenced or demarcated space.

**Comment by hungerburg** [comment]
> those areas are part of a commercial/retail landuse, park or pedestrian area.

Maybe that is so where you live. I'd prefer leisure green :)

**Comment by IgorEliezer** [comment]
> Maybe that is so where you live. I'd prefer leisure green :)

Where else would a seating area be found?

**Comment by hungerburg** [comment]
> Where else would a seating area be found?

They are everywhere, residential, meadow, industrial, &c :) Not all the world is mapped in such details as the Netherlands, so even on blank space. Still, you might be right, forget about the area, just draw the circumference - All the more reason to match the colour of the icon.

**Comment by IgorEliezer** [comment]
> They are everywhere, residential, meadow, industrial,

If they are everywhere, then they are _also_ in places that I mentioned. It's not exclusive to where I live to find seating areas only in "commercial/retail landuse, park or pedestrian". My point is that, since a seating area usually blends with or is integrated to the surrounding area, the seating area could have the same color as its surroundings. I don't think this amenity is so prominent to have a color of its own.

But leisure green does the trick too. :)

**Comment by hungerburg** [comment]
I mapped some of those as areas, because 2D adds information: E.g. may there be sun in the afternoon? In case it goes around a corner. I proposed leisure green, this does not say that there is a lawn there, just like commercial red does not mean, there are roses there. The specific tint better might be up to the cartographers. For the mock-up I just used brightness 128 twice in Gimp for the area.

**Comment by BertMule** [comment]
It still amazes me that after more than a year, and several detailed proposals, this has not been implemented.

The discussion has takes yet more time and energy than an actual implementation. Any implementation.

How does this work?
Does somebody have to give a green light?
Does someone just implement something and makes a pull-request?
Why are issues more often than not stalled? For years. For decades even.

Yet another example I have just been working on.
The seating-area is invisible, foot-paths leading to it seem go nowhere.
I don't want to be forced to add an extra layer of pavement, just because the actually relevant seating-area isn't really rendered.
[Wijdenes](https://www.openstreetmap.org/#map=19/52.62422/5.15580)

**Comment by imagico** [comment]
> Does someone just implement something and makes a pull-request?

Yes, that is typically the way issues are resolved here.  

> Why are issues more often than not stalled? For years. For decades even.

Because no one so far has been sufficiently motivated to invest the time and energy to develop a viable solution for the issue.

In case of this issue it is also likely a lot of experienced designers do not consider this a practicable idea.  As the opening comment says:

> Outdoor Seating Areas can be very well defined by a terrace, fences, hedges, or whatever.
In that case I draw it along those boundaries.

We would evidently want to primarily render whatever physical structure is present to delineate the outdoor seating (whether that is explicitly mapped with a separate feature or implicitly for example with `outdoor_seating=*`).  The rendering of `leisure=outdoor_seating` itself therefore needs to be done in a way that does not interfere with that.

This issue is still open because no one is convinced so far that this is not viable.  But it is also not clear that it is.

**Comment by BertMule** [comment]
As said, I would be happy with ANY coloured area.
Green, or perhaps commercial red.

What are we talking about? For years. Just a simple coloured area.

I just have drawn some seating in the Retiro park, Madrid.
They are big areas surrounding cabins.
Currently they still get 'lost in the woods' as a mere icon.
Here is one at the [Mirador](https://www.openstreetmap.org/#map=19/40.414709/-3.682567).
